### ISSUE TITLE
Interface showing block #0 and pending relays that have already been proved

### ISSUE THREAD

**Issue by strobus** [itsnoproblem/pokt-calculator#48]
Not sure if there is somewhere else I should report this?

**Comment by itsnoproblem** [comment]
Thanks for the report @strobus - I missed these until just now.  You can report here.  I will be opening a discord soon so we can troubleshoot stuff like this in realtime.  I'll announce it in the official pokt discord and in the README here when it's ready.

I believe this problem was happening due to isssues with the pocket endpoint I was using, and has since been resolved.
